// Generated by CoffeeScript 1.7.1
(function() {
  var Animator, DIAMETER, DIM_COLOR, GROUP_PLAY_COLOR, INNER_DIAMETER, MAIN_COLOR, NOTES, NOTE_DECAY, NOTE_RADIUS, NOTE_TRANSITION_DELAY, PLAY_COLOR, PLAY_NOTE_RADIUS, PLAY_STROKE, RadMusic, WEB_STROKE;

  DIAMETER = 700;

  INNER_DIAMETER = 150;

  NOTES = 84;

  NOTE_RADIUS = 8;

  WEB_STROKE = 4;

  PLAY_NOTE_RADIUS = 14;

  PLAY_STROKE = 7;

  PLAY_COLOR = "#FD405E";

  GROUP_PLAY_COLOR = "#A94DF0";

  MAIN_COLOR = "#9ea2b8";

  DIM_COLOR = "#494E6B";

  NOTE_TRANSITION_DELAY = 100;

  NOTE_DECAY = 200;

  RadMusic = (function() {
    function RadMusic(diameter, innerDiameter, notes) {
      this.diameter = diameter != null ? diameter : DIAMETER;
      this.innerDiameter = innerDiameter != null ? innerDiameter : INNER_DIAMETER;
      this.notes = notes != null ? notes : NOTES;
      this.midiRefs = {};
      this.groupkeys = [];
      this.animator = new Animator(PLAY_COLOR);
      this.groupanimator = new Animator(GROUP_PLAY_COLOR);
    }

    RadMusic.prototype.render = function(el) {
      this.svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      this.svg.setAttribute("width", this.diameter);
      this.svg.setAttribute("height", this.diameter);
      this.drawNotes();
      this.drawNoteLabels();
      el.appendChild(this.svg);
      return this.update();
    };

    RadMusic.prototype.drawKey = function(key, scale) {
      var count, i, k, l, ref, _i, _len, _ref, _results;
      _ref = this.midiRefs;
      for (k in _ref) {
        ref = _ref[k];
        ref.setAttribute("fill", DIM_COLOR);
      }
      count = 0;
      _results = [];
      for (_i = 0, _len = scale.length; _i < _len; _i++) {
        l = scale[_i];
        if (l === "W") {
          count += 2;
        }
        if (l === "H") {
          count += 1;
        }
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (i = _j = -1; _j <= 6; i = ++_j) {
            _results1.push((_ref1 = this.midiRefs[24 + parseInt(key) + 12 * i + count]) != null ? _ref1.setAttribute("fill", MAIN_COLOR) : void 0);
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    RadMusic.prototype.drawNotes = function() {
      var circle, circles, i, line, lines, o, r, x, xx, y, yy, _i, _ref;
      circles = document.createElementNS("http://www.w3.org/2000/svg", "g");
      lines = document.createElementNS("http://www.w3.org/2000/svg", "g");
      xx = yy = null;
      for (i = _i = 0, _ref = this.notes; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        o = -1 * (Math.PI / 6 * (i % 12) - Math.PI);
        r = (this.innerDiameter + i * (this.diameter - 70 - this.innerDiameter) / this.notes) / 2;
        x = this.diameter / 2 + r * Math.sin(o);
        y = this.diameter / 2 + r * Math.cos(o);
        circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        circle.setAttribute("r", NOTE_RADIUS);
        circle.setAttribute("fill", MAIN_COLOR);
        circle.setAttribute("cx", x);
        circle.setAttribute("cy", y);
        circles.appendChild(circle);
        this.midiRefs[i + 24] = circle;
        if (xx) {
          line = document.createElementNS("http://www.w3.org/2000/svg", "line");
          line.setAttribute("x1", xx);
          line.setAttribute("y1", yy);
          line.setAttribute("x2", x);
          line.setAttribute("y2", y);
          line.setAttribute("stroke-width", WEB_STROKE);
          line.setAttribute("stroke", DIM_COLOR);
          lines.appendChild(line);
        }
        xx = x;
        yy = y;
      }
      this.svg.appendChild(lines);
      return this.svg.appendChild(circles);
    };

    RadMusic.prototype.drawNoteLabels = function() {
      var i, labels, o, text, _i, _ref, _results;
      labels = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
      _results = [];
      for (i = _i = 0, _ref = labels.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        text = document.createElementNS("http://www.w3.org/2000/svg", "text");
        o = -1 * (Math.PI / 6 * (i % 12) - Math.PI);
        text.setAttribute("x", this.diameter / 2 + Math.sin(o) * (this.diameter - 30) / 2);
        text.setAttribute("y", this.diameter / 2 + Math.cos(o) * (this.diameter - 30) / 2);
        text.setAttribute("text-anchor", "middle");
        text.setAttribute("fill", DIM_COLOR);
        text.textContent = labels[i];
        _results.push(this.svg.appendChild(text));
      }
      return _results;
    };

    RadMusic.prototype.press = function(key) {
      var circle, delay, keypress;
      circle = this.midiRefs[key];
      keypress = {
        key: key,
        x: parseInt(circle.getAttribute("cx")),
        y: parseInt(circle.getAttribute("cy")),
        pressedAt: Date.now()
      };
      this.groupkeys.push(keypress);
      delay = function() {
        var _i, _len, _ref;
        if (this.groupkeys.length === 1) {
          this.animator.addKeyPress(this.groupkeys[0]);
        } else if (this.groupkeys.length > 1) {
          _ref = this.groupkeys;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            keypress = _ref[_i];
            this.groupanimator.addKeyPress(keypress);
          }
        }
        return this.groupkeys = [];
      };
      return setTimeout(delay.bind(this), 40);
    };

    RadMusic.prototype.unpress = function(key) {
      this.animator.removeKeyPress(key);
      return this.groupanimator.removeKeyPress(key);
    };

    RadMusic.prototype.update = function() {
      this._clear();
      this.animator.update();
      this.groupanimator.update();
      return requestAnimationFrame(this.update.bind(this));
    };

    RadMusic.prototype._clear = function() {
      if (this.animations) {
        this.svg.removeChild(this.animations);
      }
      if (this.animations) {
        this.animations.innerHTML = "";
      }
      this.animations = document.createElementNS("http://www.w3.org/2000/svg", "g");
      this.svg.appendChild(this.animations);
      this.animator.setLayerElement(this.animations);
      return this.groupanimator.setLayerElement(this.animations);
    };

    return RadMusic;

  })();

  Animator = (function() {
    function Animator(color) {
      this.color = color != null ? color : PLAY_COLOR;
      this.keyPresses = {};
    }

    Animator.prototype.addKeyPress = function(keyPress) {
      if (!this.keyPresses[keyPress.key]) {
        return this.keyPresses[keyPress.key] = keyPress;
      }
    };

    Animator.prototype.removeKeyPress = function(key) {
      var _ref;
      return (_ref = this.keyPresses[key]) != null ? _ref.unpressedAt = Date.now() : void 0;
    };

    Animator.prototype.update = function() {
      var count, key, keyPress, life, now, other, otherKey, press, pressedKey, x, y, _ref, _ref1, _ref2, _ref3, _results, _results1;
      now = Date.now();
      _ref = this.keyPresses;
      for (key in _ref) {
        keyPress = _ref[key];
        if (now - keyPress.unpressedAt > NOTE_DECAY) {
          delete this.keyPresses[key];
        }
      }
      count = Object.keys(this.keyPresses).length;
      if (count === 0) {
        return "idle";
      }
      if (count === 1) {
        _ref1 = this.keyPresses;
        _results = [];
        for (key in _ref1) {
          keyPress = _ref1[key];
          life = now - keyPress.pressedAt;
          if (life < 500) {
            this._drawGlowerAt(keyPress.x, keyPress.y, 8 + 4 * life / 500, 1 - life / 500);
          }
          _results.push(this._drawNoteAt(keyPress.x, keyPress.y));
        }
        return _results;
      } else {
        _ref2 = this.keyPresses;
        _results1 = [];
        for (pressedKey in _ref2) {
          press = _ref2[pressedKey];
          life = now - press.pressedAt;
          _ref3 = this.keyPresses;
          for (otherKey in _ref3) {
            other = _ref3[otherKey];
            if (otherKey !== pressedKey) {
              if (life < NOTE_TRANSITION_DELAY) {
                x = other.x - (other.x - press.x) * life / NOTE_TRANSITION_DELAY;
                y = other.y - (other.y - press.y) * life / NOTE_TRANSITION_DELAY;
                this._drawNoteAt(x, y);
                this._drawLine(other.x, other.y, x, y);
              } else if (now - other.pressedAt >= NOTE_TRANSITION_DELAY) {
                this._drawLine(other.x, other.y, press.x, press.y);
              }
            }
          }
          if ((NOTE_TRANSITION_DELAY <= life && life < 700)) {
            this._drawGlowerAt(press.x, press.y, PLAY_NOTE_RADIUS + 8 * (life - 50) / 500, 1 - (life - 50) / 500);
            this._drawNoteAt(press.x, press.y);
          }
          if (life >= 700) {
            _results1.push(this._drawNoteAt(press.x, press.y));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      }
    };

    Animator.prototype.setLayerElement = function(svg) {
      return this.svg = svg;
    };

    Animator.prototype._drawGlowerAt = function(x, y, size, opacity) {
      return this._drawCircle(x, y, size, opacity, "#fff");
    };

    Animator.prototype._drawNoteAt = function(x, y, size, opacity) {
      if (size == null) {
        size = PLAY_NOTE_RADIUS;
      }
      if (opacity == null) {
        opacity = 1;
      }
      return this._drawCircle(x, y, size, opacity, this.color);
    };

    Animator.prototype._drawCircle = function(x, y, size, opacity, fill) {
      var circle;
      circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
      circle.setAttribute("r", size);
      circle.setAttribute("fill", fill);
      circle.setAttribute("cx", x);
      circle.setAttribute("cy", y);
      circle.setAttribute("fill-opacity", opacity);
      return this.svg.appendChild(circle);
    };

    Animator.prototype._drawLine = function(x1, y1, x2, y2) {
      var line;
      line = document.createElementNS("http://www.w3.org/2000/svg", "line");
      line.setAttribute("x1", x1);
      line.setAttribute("y1", y1);
      line.setAttribute("x2", x2);
      line.setAttribute("y2", y2);
      line.setAttribute("stroke-width", PLAY_STROKE);
      line.setAttribute("stroke", this.color);
      line.setAttribute("stroke-opacity", "0.4");
      return this.svg.appendChild(line);
    };

    return Animator;

  })();

  window.RadMusic = RadMusic;

}).call(this);
